# Generated by Django 2.2.5 on 2021-02-28 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
